# Generated by Django 3.1.7 on 2021-05-16 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0005_auto_20210516_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
