# Generated by Django 3.1.7 on 2021-05-16 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0006_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='100', max_digits=10, validators=[django.core.validators.MinLengthValidator(2, 'کمترین قیمت 10 هزار تومان میباشد')], verbose_name='قیمت'),
            preserve_default=False,
        ),
    ]
