# Generated by Django 3.1.7 on 2021-05-17 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0010_auto_20210518_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productId',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
