# Generated by Django 3.1.7 on 2021-05-17 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0011_product_productid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='productId',
            new_name='objid',
        ),
    ]
