# Generated by Django 3.1.7 on 2021-05-17 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0012_auto_20210518_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='objid',
            field=models.CharField(default='d', editable=False, max_length=10),
            preserve_default=False,
        ),
    ]
