# Generated by Django 3.1.7 on 2021-05-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0016_auto_20210518_0416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='objid',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
