# Generated by Django 3.1.7 on 2021-05-18 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0017_auto_20210518_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'For Mens'), ('Women', 'For Womens')], default='Men', max_length=10, verbose_name='برای'),
        ),
    ]
