# Generated by Django 3.1.7 on 2021-05-18 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0018_product_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('Men', 'آقایان'), ('Women', 'خانم ها')], default='Men', max_length=10, verbose_name='برای'),
        ),
    ]
