# Generated by Django 3.1.7 on 2021-05-18 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0019_auto_20210518_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'آقایان'), ('women', 'خانم ها'), ('child', 'بچکانه'), ('baby', 'نوزاد')], default='men', max_length=10, verbose_name='برای'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large'), ('XXXL', 'XXX-Large'), ('all', 'تمامی سایز ها')], default='M', max_length=4, verbose_name='سایز لباس'),
        ),
    ]
