# Generated by Django 3.1.7 on 2021-05-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0020_auto_20210518_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='beExist',
            field=models.CharField(choices=[('True', 'موجود'), ('False', 'نا موجود')], default='True', max_length=10, verbose_name='موجودی'),
        ),
    ]
