# Generated by Django 3.1.7 on 2021-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0021_product_beexist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'آقایان'), ('women', 'خانم ها')], default='men', max_length=10, verbose_name='برای'),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'X-Large'), ('XXL', 'XX-Large'), ('XXXL', 'XXX-Large'), ('child', 'بچکانه'), ('baby', 'نوزاد'), ('all', 'تمامی سایز ها')], default='M', max_length=10, verbose_name='سایز لباس'),
        ),
    ]
