# Generated by Django 3.1.7 on 2021-05-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0022_auto_20210518_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('men', 'آقایان'), ('women', 'خانم ها'), ('sport', 'اسپرت')], default='men', max_length=10, verbose_name='برای'),
        ),
    ]
