# Generated by Django 3.1.7 on 2021-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0025_auto_20210518_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Xlarge'), ('XXL', 'Xxlarge'), ('XXXL', 'Xxxlarge'), ("[('fr', ('S', 'Small')), ('fr', ('S', 'Small'))]", 'Adultlist'), ('child', 'بچکانه'), ('baby', 'نوزاد'), ('all', 'تمامی سایز ها')], default='M', max_length=60, verbose_name='سایز لباس'),
        ),
    ]
