# Generated by Django 3.1.7 on 2021-05-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0027_auto_20210518_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ("[('re', ('r', 'reza'))]", 'S'), ('L', 'Large'), ('XL', 'Xlarge'), ('XXL', 'Xxlarge'), ('XXXL', 'Xxxlarge'), ("[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')]", 'Media Choices'), ('child', 'بچکانه'), ('baby', 'نوزاد'), ('all', 'تمامی سایز ها')], default='M', max_length=500, verbose_name='سایز لباس'),
        ),
    ]
