# Generated by Django 3.1.7 on 2021-05-19 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0006_remove_tag_products'),
        ('eshop_products', '0030_auto_20210518_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='eshop_tag.Tag', verbose_name='برچسب ها'),
        ),
    ]
