# Generated by Django 3.1.7 on 2021-05-19 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0031_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
    ]
