# Generated by Django 3.1.7 on 2021-05-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_seller', '0001_initial'),
        ('eshop_products', '0035_productgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='eshop_seller.seller', verbose_name='فروشنده'),
            preserve_default=False,
        ),
    ]
