# Generated by Django 3.1.7 on 2021-05-23 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0037_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=302, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=50, verbose_name='ایمیل')),
                ('rate', models.IntegerField(choices=[(0, 'nothing'), (1, 'میپسندم'), (-1, 'نمیپسندم')], default=0, verbose_name='رتبه')),
                ('text', models.TextField(max_length=1000, verbose_name='متن پیام')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='eshop_products.product', verbose_name='مربوط به محصولِ')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
    ]
