# Generated by Django 3.1.7 on 2021-05-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0039_commentproduct_timess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='timess',
        ),
    ]
