# Generated by Django 3.1.7 on 2021-05-24 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eshop_products', '0040_remove_commentproduct_timess'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='userid',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user', verbose_name='ایدی فرد نظر دهنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentproduct',
            name='username',
            field=models.CharField(default='1', max_length=120, verbose_name='نام کاربری فرد نظر دهنده'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commentproduct',
            name='rate',
            field=models.IntegerField(choices=[(0, 'نظری ندارم'), (1, 'میپسندم'), (-1, 'نمیپسندم')], default=0, verbose_name='رتبه'),
        ),
    ]
