# Generated by Django 3.1.7 on 2021-05-25 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0041_auto_20210525_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentproduct',
            old_name='userid',
            new_name='userobject',
        ),
    ]
