# Generated by Django 3.1.7 on 2021-05-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0042_auto_20210525_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentproduct',
            name='username',
        ),
    ]
