# Generated by Django 3.1.7 on 2021-05-25 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0043_remove_commentproduct_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='seller',
            new_name='Contact',
        ),
    ]
