# Generated by Django 3.1.7 on 2021-05-25 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0044_auto_20210525_1930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Contact',
            new_name='seller',
        ),
    ]
