# Generated by Django 3.1.7 on 2021-05-31 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0049_product_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='beExist',
            field=models.BooleanField(choices=[('True', 'موجود'), ('False', 'نا موجود')], default='True', max_length=10, verbose_name='موجودی'),
        ),
    ]
