# Generated by Django 3.1.7 on 2021-05-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0051_auto_20210531_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='most_count',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
    ]
