# Generated by Django 3.1.7 on 2021-05-31 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0052_product_most_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='most_count',
            new_name='visit_count',
        ),
    ]
