services:
  app:
    build: .
    command: sh -c "python manage.py migrate && gunicorn A.wsgi -b 0.0.0.0:8000"
    container_name: app
    volumes:
      - .:/code/
      - ./static_cdn:/code/static_cdn
    ports:
      - "8000:8000"
    networks:
      - main
    restart: always

  nginx:
    container_name: nginx
    command: nginx -g "daemon off;"
    image: nginx
    depends_on:
      - app
    networks:
      - main
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static_cdn:/static/

networks:
  main:


