# Generated by Django 3.1.7 on 2021-05-15 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size2',
            field=models.IntegerField(choices=[(1, 'Xxsmall'), (2, 'Small'), (3, 'Medium'), (4, 'Large'), (5, 'Xlarge'), (6, 'Xxlarge')], default=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
