# Generated by Django 3.1.7 on 2021-05-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_account', '0004_auto_20210516_0457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
