# Generated by Django 3.1.7 on 2021-05-23 15:47

from django.db import migrations, models
import eshop_seller.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shopName', models.CharField(max_length=50, verbose_name='نام فروشگاه')),
                ('firstName', models.CharField(max_length=50, verbose_name='نام')),
                ('lastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('image', models.ImageField(upload_to=eshop_seller.models.upload_image_path, verbose_name='پروفایل')),
                ('bio', models.TextField(max_length=400, verbose_name='درباره')),
                ('address', models.TextField(max_length=400, verbose_name='آدرس')),
                ('mobile', models.CharField(max_length=13, verbose_name='شماره موبایل')),
                ('tel', models.CharField(blank=True, max_length=13, verbose_name='شماره تلفن')),
                ('instagram', models.CharField(default='https://instagram.com', max_length=50, verbose_name='آیدی اینستاگرام')),
                ('telegram', models.CharField(default='https://telegram.org', max_length=50, verbose_name='آیدی تلگرام')),
                ('soroush', models.CharField(default='https://hi.splus.ir', max_length=50, verbose_name='آیدی سروش')),
                ('github', models.CharField(default='https://github.com', max_length=50, verbose_name='آیدی گیتهاب')),
                ('linkdin', models.CharField(default='https://linkdin.com', max_length=50, verbose_name='آیدی لینکدین')),
            ],
            options={
                'verbose_name': 'فروشنده',
                'verbose_name_plural': 'فروشندگان',
            },
        ),
    ]
