# Generated by Django 3.1.7 on 2021-05-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_seller', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='active',
            field=models.BooleanField(default=True, verbose_name='فعال/غیر فعال'),
        ),
    ]
