# Generated by Django 3.1.7 on 2021-05-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0002_auto_20210519_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(verbose_name='اسلاگ'),
        ),
    ]
