# Generated by Django 3.1.7 on 2021-05-19 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0005_auto_20210519_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
