# Generated by Django 3.1.7 on 2021-05-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0032_remove_product_tags'),
        ('eshop_tag', '0006_remove_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='products',
            field=models.ManyToManyField(blank=True, to='eshop_products.Product', verbose_name='محصولات مشمول'),
        ),
    ]
