# Generated by Django 3.1.7 on 2021-05-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_tag', '0007_tag_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='products',
        ),
    ]
