# Generated by Django 3.1.7 on 2021-06-08 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_contacts', '0002_newslettersemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersemail',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='حذف شده/موجود'),
        ),
    ]
