# Generated by Django 3.1.7 on 2021-05-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='s', max_length=50, verbose_name='نام شرکت پرداخت')),
                ('gatewaySite', models.URLField(verbose_name='آدرس سایت پرداخت')),
                ('clientURL', models.URLField(verbose_name='لینک درگاه پرداخت()')),
                ('startPayURL', models.URLField(verbose_name='آدرس شروع پرداخت')),
                ('merchantID', models.CharField(default='none', max_length=100, verbose_name='کد درگاه پرداخت(Merchant-ID)')),
                ('callBackUrl', models.URLField(default='payment/verify/1', verbose_name='لینک بازگشت')),
                ('domain', models.CharField(default='localhost:8000/', max_length=50, verbose_name='آدرس دامنه')),
                ('active', models.BooleanField(default=True, verbose_name='فعال / غیرفعال')),
            ],
            options={
                'verbose_name': 'درگاه پرداخت',
                'verbose_name_plural': 'درگاه های پرداخت',
            },
        ),
    ]
