# Generated by Django 3.1.7 on 2021-05-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_payment', '0003_auto_20210531_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentgateway',
            name='gatewayLogoScript',
            field=models.TextField(default='d', verbose_name='اسکریپت اعتماد'),
            preserve_default=False,
        ),
    ]
