# Generated by Django 3.1.7 on 2021-05-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_payment', '0006_auto_20210531_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentgateway',
            name='clientURL',
            field=models.URLField(verbose_name='لینک درگاه پرداخت (Client)'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='merchantID',
            field=models.CharField(default='none', max_length=100, verbose_name='کد درگاه پرداخت (Merchant-ID)'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='server',
            field=models.CharField(default='localhost:8000/', max_length=50, verbose_name='آدرس سرور (Server)'),
        ),
        migrations.AlterField(
            model_name='paymentgateway',
            name='startPayURL',
            field=models.URLField(verbose_name='آدرس شروع پرداخت (Start pay)'),
        ),
    ]
