# Generated by Django 3.1.7 on 2021-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.SlugField(default='kikiriki', max_length=20, verbose_name='عنوان در url'),
            preserve_default=False,
        ),
    ]
