# Generated by Django 3.1.7 on 2021-05-20 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products_category', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCatergory',
            new_name='ProductCategory',
        ),
    ]
