# Generated by Django 3.1.7 on 2021-05-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import eshop_sitesetting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان سایت')),
                ('titleEnglish', models.CharField(max_length=150, verbose_name='Title')),
                ('address', models.TextField(max_length=500, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل سایت')),
                ('mobile', models.CharField(max_length=14, verbose_name='موبایل سایت')),
                ('tel', models.CharField(max_length=14, verbose_name='تلفن سایت')),
                ('fax', models.CharField(max_length=14, verbose_name='فکس سایت')),
                ('aboutus', models.TextField(max_length=1000, verbose_name='درباره ما')),
                ('copyright', models.CharField(default='تمامی حقوق این وب سایت متعلق به سایت <django.db.models.fields.CharField> و فرد <django.db.models.fields.related.ForeignKey> میباشد', max_length=200, verbose_name='قانون کپی رایت')),
                ('logo', models.ImageField(upload_to=eshop_sitesetting.models.upload_image_path, verbose_name='لوگو سایت (51*180)')),
                ('active', models.BooleanField(default=True, verbose_name='فعال/غیرفعال')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='مالک سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'مدیریت تنظیمات',
            },
        ),
    ]
