# Generated by Django 3.1.7 on 2021-05-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(default='', max_length=50, verbose_name='اینستاگرام'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(default='', max_length=50, verbose_name='تلگرام'),
        ),
    ]
