# Generated by Django 3.1.7 on 2021-05-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0002_auto_20210526_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='instagram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تلگرام'),
        ),
    ]
