# Generated by Django 3.1.7 on 2021-05-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0003_auto_20210526_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesetting',
            old_name='logo',
            new_name='image',
        ),
    ]
