# Generated by Django 3.1.7 on 2021-05-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0005_auto_20210527_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='mapurl',
            field=models.URLField(blank=True, default='https://google.com', null=True),
        ),
    ]
