# Generated by Django 3.1.7 on 2021-05-27 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0006_sitesetting_mapurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='mapurl',
            field=models.URLField(verbose_name='نشانی فروشگاه/دفتر'),
        ),
    ]
