# Generated by Django 3.1.7 on 2021-05-31 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sitesetting', '0007_auto_20210528_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='tax_of_sell',
            field=models.PositiveSmallIntegerField(default=9, verbose_name='درصد مالیات بر فروش محصولات'),
        ),
    ]
