# Generated by Django 3.1.7 on 2021-05-22 23:43

from django.db import migrations, models
import eshop_sliders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Silder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleYellow', models.CharField(max_length=70, verbose_name='عنوان')),
                ('titleWhite', models.CharField(blank=True, max_length=70, verbose_name='عنوان دوم')),
                ('desc', models.TextField()),
                ('link', models.URLField(max_length=150, verbose_name='لینک')),
                ('image', models.ImageField(upload_to=eshop_sliders.models.upload_image_path, verbose_name='تصویر')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلایدر',
                'verbose_name_plural': 'اسلایدر',
            },
        ),
    ]
