# Generated by Django 3.1.7 on 2021-05-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silder',
            old_name='titleYellow',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='silder',
            name='titleWhite',
        ),
    ]
