# Generated by Django 3.1.7 on 2021-05-22 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0002_auto_20210523_0414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='silder',
            old_name='title',
            new_name='titleYellow',
        ),
    ]
