# Generated by Django 3.1.7 on 2021-05-22 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0003_auto_20210523_0414'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Silder',
        ),
    ]
