# Generated by Django 3.1.7 on 2021-05-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0005_silde'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Silde',
            new_name='Slide',
        ),
    ]
