# Generated by Django 3.1.7 on 2021-05-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0007_slide_titlewhite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='titleYellow',
            new_name='title',
        ),
    ]
