# Generated by Django 3.1.7 on 2021-05-22 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0009_auto_20210523_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='desc',
            field=models.TextField(max_length=250, verbose_name='توضیحات'),
        ),
    ]
