# Generated by Django 3.1.7 on 2021-05-29 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_products', '0049_product_timestamp'),
        ('eshop_sliders', '0010_auto_20210523_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='product',
            field=models.ForeignKey(blank=True, default='1', on_delete=django.db.models.deletion.CASCADE, to='eshop_products.product', verbose_name='محصول'),
            preserve_default=False,
        ),
    ]
