# Generated by Django 3.1.7 on 2021-05-29 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_sliders', '0011_slide_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='link',
        ),
    ]
