# Generated by Django 3.1.7 on 2021-05-31 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop_order', '0003_auto_20210531_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ref_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, verbose_name='کد پیگیری پرداخت'),
        ),
    ]
